In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df=pd.read_csv('Iris.csv')

In [ ]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
df['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_csv('Iris.csv')
y = df['Species']
x = df.drop(['Id', 'Species'], axis=1)

In [ ]:
x=df.drop('Id',axis=1)

In [ ]:
x

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
Xtrain,X_test,y_train,y_test=train_test_split(x, y, test_size=0.33, random_state=42)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
m_knn=KNeighborsClassifier(n_neighbors=5)

In [ ]:
# Re-prepare features and target to ensure no string columns in X
y = df['Species']
x = df.drop(['Id', 'Species'], axis=1)

# Re-split the data
Xtrain, X_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

# Now fit the model
m_knn.fit(Xtrain, y_train)

KNeighborsClassifier()

In [ ]:
m_knn.score(X_test,y_test)

0.98

In [ ]:
from sklearn.svm import SVC
sv=SVC(C=10,kernel='rbf',gamma='auto')
sv.fit(Xtrain,y_train)

SVC(C=10, gamma='auto')

In [ ]:
sv.score(X_test,y_test)

1.0

**now using grid search cv**

In [ ]:
from sklearn.model_selection import GridSearchCV
classi=GridSearchCV((sv),{
    'C':[1,10,20,30],
    'kernel':['rbf','linear']
},cv=5,return_train_score=False)

In [ ]:
classi.fit(x,y)

GridSearchCV(cv=5, estimator=SVC(C=10, gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [ ]:
classi.cv_results_

{'mean_fit_time': array([0.0031395 , 0.00293827, 0.0035358 , 0.0028441 , 0.00320482,
        0.0034977 , 0.00275702, 0.00298328]),
 'std_fit_time': array([0.0003577 , 0.00025707, 0.00090216, 0.0003814 , 0.00035926,
        0.00024821, 0.00014318, 0.00048592]),
 'mean_score_time': array([0.00242066, 0.00216494, 0.00220079, 0.00244603, 0.00218287,
        0.00263348, 0.0020205 , 0.00215936]),
 'std_score_time': array([0.00012503, 0.00030266, 0.00025991, 0.00046943, 0.00019423,
        0.00037364, 0.00010914, 0.0002681 ]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [ ]:
r=pd.DataFrame(classi.cv_results_)

In [ ]:
r

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003139,0.000358,0.002421,0.000125,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.002938,0.000257,0.002165,0.000303,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.003536,0.000902,0.002201,0.000260,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.002844,0.000381,0.002446,0.000469,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.003205,0.000359,0.002183,0.000194,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.003498,0.000248,0.002633,0.000374,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.002757,0.000143,0.002021,0.000109,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.002983,0.000486,0.002159,0.000268,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [ ]:
r[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

In [ ]:
from sklearn.model_selection import RandomizedSearchCV

In [ ]:
classi_r=RandomizedSearchCV((sv),{
    'C':[1,10,20,30],
    'kernel':['rbf','linear']
},n_iter=4,cv=5,return_train_score=False)

In [ ]:
classi_r.fit(x,y)

RandomizedSearchCV(cv=5, estimator=SVC(C=10, gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [ ]:
r1=pd.DataFrame(classi_r.cv_results_)

In [ ]:
r1

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.012872,0.005694,0.008442,0.002582,linear,10,"{'kernel': 'linear', 'C': 10}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,2
1,0.004806,0.000532,0.003792,0.000590,rbf,10,"{'kernel': 'rbf', 'C': 10}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.004692,0.000478,0.003354,0.000248,rbf,20,"{'kernel': 'rbf', 'C': 20}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,3
3,0.005305,0.002269,0.004260,0.001967,linear,30,"{'kernel': 'linear', 'C': 30}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,4

In [ ]:
r1[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0       10       linear         0.973333
1       10          rbf         0.980000
2       20          rbf         0.966667
3       30       linear         0.960000