In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns

In [ ]:
df=pd.read_csv('Titanic-Dataset.csv')

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
df['Age'].fillna(df['Age'].mean(),inplace=True)

/tmp/ipykernel_1910/694922604.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(),inplace=True)

In [ ]:
df.drop(['Cabin'], axis=1, inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(4)
memory usage: 76.7+ KB

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [ ]:
df['Sex']=le.fit_transform(df['Sex'])
df['Embarked']=le.fit_transform(df['Embarked'])

In [ ]:
df['Name'].dropna(inplace=True)

In [ ]:
df.drop(['Name'],axis=1,inplace=True)
df.drop(['Ticket'],axis=1,inplace=True)

In [ ]:
df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,1,0,3,1,22.000000,1,0,7.2500,2
1,2,1,1,0,38.000000,1,0,71.2833,0
2,3,1,3,0,26.000000,0,0,7.9250,2
3,4,1,1,0,35.000000,1,0,53.1000,2
4,5,0,3,1,35.000000,0,0,8.0500,2
...,...,...,...,...,...,...,...,...,...
886,887,0,2,1,27.000000,0,0,13.0000,2
887,888,1,1,0,19.000000,0,0,30.0000,2
888,889,0,3,0,29.699118,1,2,23.4500,2
889,890,1,1,1,26.000000,0,0,30.0000,0
890,891,0,3,1,32.000000,0,0,7.7500,1

In [ ]:
df=df.astype(int)

In [ ]:
df

     PassengerId  Survived  Pclass  Sex  Age  SibSp  Parch  Fare  Embarked
0              1         0       3    1   22      1      0     7         2
1              2         1       1    0   38      1      0    71         0
2              3         1       3    0   26      0      0     7         2
3              4         1       1    0   35      1      0    53         2
4              5         0       3    1   35      0      0     8         2
..           ...       ...     ...  ...  ...    ...    ...   ...       ...
886          887         0       2    1   27      0      0    13         2
887          888         1       1    0   19      0      0    30         2
888          889         0       3    0   29      1      2    23         2
889          890         1       1    1   26      0      0    30         0
890          891         0       3    1   32      0      0     7         1

[891 rows x 9 columns]

In [ ]:
x=df.drop(['Survived'],axis=1)
y=df['Survived']

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [ ]:
y_p=model.predict(X_test)

In [ ]:
y_p

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1])

In [ ]:
y_test

709    1
439    0
840    0
720    1
39     1
      ..
433    0
773    0
25     1
84     1
10     1
Name: Survived, Length: 179, dtype: int64

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [ ]:
accuracy_score(y_test,y_p)

0.770949720670391

In [ ]:
confusion_matrix(y_test,y_p)

array([[87, 18],
       [23, 51]])

In [ ]:
classification_report(y_test,y_p)

'              precision    recall  f1-score   support\n\n           0       0.79      0.83      0.81       105\n           1       0.74      0.69      0.71        74\n\n    accuracy                           0.77       179\n   macro avg       0.77      0.76      0.76       179\nweighted avg       0.77      0.77      0.77       179\n'

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

In [ ]:
x_sc=sc.fit_transform(X_train)
xt_sc=sc.fit_transform(X_test)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(x_sc,y_train)

KNeighborsClassifier()

In [ ]:
y_pr_knn=knn.predict(xt_sc)

In [ ]:
accuracy_score(y_test,y_pr_knn)

0.8044692737430168

In [ ]:
confusion_matrix(y_test,y_pr_knn)

array([[92, 13],
       [22, 52]])

In [ ]:
classification_report(y_test,y_pr_knn)

'              precision    recall  f1-score   support\n\n           0       0.81      0.88      0.84       105\n           1       0.80      0.70      0.75        74\n\n    accuracy                           0.80       179\n   macro avg       0.80      0.79      0.79       179\nweighted avg       0.80      0.80      0.80       179\n'

In [ ]:
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()
nb.fit(X_train,y_train)

GaussianNB()

In [ ]:
y_pr_nb=nb.predict(X_test)
y_pr_nb

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1])

In [ ]:
accuracy_score(y_test,y_pr_nb)

0.776536312849162

In [ ]:
confusion_matrix(y_test,y_pr_nb)

array([[82, 23],
       [17, 57]])

In [ ]:
classification_report(y_test,y_pr_nb)

'              precision    recall  f1-score   support\n\n           0       0.83      0.78      0.80       105\n           1       0.71      0.77      0.74        74\n\n    accuracy                           0.78       179\n   macro avg       0.77      0.78      0.77       179\nweighted avg       0.78      0.78      0.78       179\n'

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier(random_state=42)
dt.fit(x_sc,y_train)

DecisionTreeClassifier(random_state=42)

In [ ]:
y_pr_dt=dt.predict(xt_sc)

In [ ]:
accuracy_score(y_test,y_pr_dt)

0.7821229050279329

In [ ]:
confusion_matrix(y_test,y_pr_dt)

array([[87, 18],
       [21, 53]])

In [ ]:
classification_report(y_test,y_pr_dt)

'              precision    recall  f1-score   support\n\n           0       0.81      0.83      0.82       105\n           1       0.75      0.72      0.73        74\n\n    accuracy                           0.78       179\n   macro avg       0.78      0.77      0.77       179\nweighted avg       0.78      0.78      0.78       179\n'

In [ ]:
from sklearn.svm import SVC
svm=SVC(kernel='rbf')
svm.fit(x_sc,y_train)

SVC()

In [ ]:
y_pr_sv=svm.predict(xt_sc)

In [ ]:
y_pr_sv

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0])

In [ ]:
accuracy_score(y_test,y_pr_sv)

0.8100558659217877

In [ ]:
confusion_matrix(y_test,y_pr_sv)

array([[93, 12],
       [22, 52]])

In [ ]:
classification_report(y_test,y_pr_sv)

'              precision    recall  f1-score   support\n\n           0       0.81      0.89      0.85       105\n           1       0.81      0.70      0.75        74\n\n    accuracy                           0.81       179\n   macro avg       0.81      0.79      0.80       179\nweighted avg       0.81      0.81      0.81       179\n'

In [ ]:
x=df.drop(['Survived'],axis=1)
y=df['Survived']

In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
sc=StandardScaler()
x_sc=sc.fit_transform(x)

In [ ]:
score=cross_val_score(svm,x_sc,y,cv=5,scoring='accuracy')

In [ ]:
score

array([0.83240223, 0.8258427 , 0.81460674, 0.79775281, 0.84269663])

In [ ]:
score.mean()

np.float64(0.8226602222082731)